# Generated by Django 5.1.4 on 2025-02-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_testrequest_company_delete_company'),
        ('windows_test_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowstestinstance',
            name='sub_tests',
            field=models.ManyToManyField(blank=True, to='dashboard.subtest'),
        ),
    ]
