# Generated by Django 5.1.4 on 2025-01-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linux_test_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxtestinstance',
            name='guacamole_connection_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
