# Generated by Django 5.1.4 on 2025-02-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_testrequest_sub_tests_testrequest_sub_tests'),
        ('linux_test_rooms', '0002_linuxtestinstance_guacamole_connection_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxtestinstance',
            name='sub_tests',
            field=models.ManyToManyField(blank=True, to='dashboard.subtest'),
        ),
    ]
