# Generated by Django 5.1.4 on 2025-01-23 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_testrequest_recorded_session_and_more'),
        ('video_playback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordedsession',
            name='test_id',
        ),
        migrations.AddField(
            model_name='recordedsession',
            name='test_request',
            field=models.OneToOneField(blank=True, help_text='Link to the test request this recording belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_session', to='dashboard.testrequest'),
        ),
        migrations.AlterField(
            model_name='recordedsession',
            name='video_path',
            field=models.CharField(help_text='Path to the video file in S3.', max_length=500),
        ),
    ]
