# Generated by Django 5.1.4 on 2025-01-23 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_testrequest_recorded_session_and_more'),
        ('video_playback', '0002_remove_recordedsession_test_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedsession',
            name='test_request',
            field=models.OneToOneField(default=1, help_text='Link to the test request this recording belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='recorded_session', to='dashboard.testrequest'),
            preserve_default=False,
        ),
    ]
