# Generated by Django 5.1.4 on 2025-01-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_playback', '0003_alter_recordedsession_test_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordedsession',
            name='test_request',
        ),
        migrations.AddField(
            model_name='recordedsession',
            name='test_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordedsession',
            name='video_path',
            field=models.CharField(max_length=500),
        ),
    ]
