services:
  web:
    image: sheemer44/prserver
    command: sh -c " python manage.py migrate && python manage.py collectstatic --noinput && python manage.py process_tasks & gunicorn --timeout 120 --bind 0.0.0.0:8000 pr_server.wsgi:application"
    volumes:
      - static_volume:/home/timango/app/staticfiles
      - /usr/bin/docker:/usr/bin/docker         
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - guac-net
    secrets:
     # - RDP_ENCRYPTION_KEY
      - SECRET_KEY
      - AWS_REGION
      - windows_key
      - GUAC_DB_HOST
      - INSTANCE_TYPE
      - KEY_NAME
      #- SECURITY_GROUP
      #- AMI_WIN_PASS
      - GUACAMOLE_SERVER
     # - DB_HOST
      - DB_USER
      - DB_NAME
      - DB_PASSWORD
      - GUACAMOLE_PASSWORD
      #- GUACAMOLE_USERNAME
      #- AWS_S3_BUCKET_NAME
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - postgres_password
      - web_postgres_password   



  webdb:
    image: postgres:15 
    restart: always
    environment:
      - POSTGRES_DB=BigBoss+ 
      - POSTGRES_USER=tim    
      - POSTGRES_PASSWORD_FILE=/run/secrets/web_postgres_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    networks:
      - guac-net
    secrets:
      - web_postgres_password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - guacamole
    volumes:
      - static_volume:/home/timango/app/staticfiles
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/nginx
      - ./error:/home/timango/app/error
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      - guac-net

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERBOSITY=-vv
    volumes:
      - ./fail2ban_config:/config
      - ./logs:/var/log:ro
    networks:
      - guac-net

  guacamole:
    image: guacamole/guacamole:1.5.5
      #configs:
      #- source: guac-webxml
      #  target: /usr/local/tomcat/webapps/guacamole/WEB-INF/web.xml
    volumes:
      - ./extensions/guacamole-auth-jdbc-postgresql-1.5.5.jar:/etc/guacamole/extensions/guacamole-auth-jdbc-postgresql-1.5.5.jar
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=guac_db
      - POSTGRES_USER=guac_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - GUACAMOLE_CORS_ALLOWED_ORIGINS=https://truetohire.com
    secrets:
      - postgres_password
    depends_on:
      - db
      - guacd
    networks:
      - guac-net
    

  guacd:
    image: guacamole/guacd:1.5.5
    networks:
      - guac-net
    volumes:
    - ./recordings:/prserver/recordings  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      - S3_BUCKET=prservervideobackup 

  custom-guac-recorder:
    image: sheemer44/custom-guac-recorder
    networks:
      - guac-net
    volumes:
      - ./recordings:/prserver/recordings
    environment:
      - S3_BUCKET=prservervideobackup

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=guac_db
      - POSTGRES_USER=guac_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - guac-net

configs:
  guac-webxml:
    external: true

networks:
  guac-net:
    driver: overlay
    attachable: true

volumes:
  static_volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgres-data:
  pgdata:
  recordings:
  logs: 
  fail2ban_config:
  letsencrypt:
  error:

secrets:
  SECRET_KEY:
    external: true
  AWS_REGION:
    external: true
  #AMI_ID:
  #  external: true
  GUAC_DB_HOST:
    external: true
  INSTANCE_TYPE:
    external: true
  windows_key:
    external: true
  KEY_NAME:
    external: true
  SECURITY_GROUP:
    external: true
  #AMI_WIN_PASS:
  #  external: true
  GUACAMOLE_SERVER:
    external: true
  #DB_HOST:
  #  external: true
  DB_USER:
    external: true
  DB_PASSWORD:
    external: true
  DB_NAME:
    external: true
  #GUACAMOLE_USERNAME:
  #  external: true
  GUACAMOLE_PASSWORD:
    external: true
  #AWS_SECRET_ACCESS_KEY:
  #  external: true
  #AWS_ACCESS_KEY_ID: 
  #  external: true
  DATABASE_NAME:
    external: true
  DATABASE_USER:
    external: true
  DATABASE_PASSWORD:
    external: true
  #DATABASE_HOST:
  #  external: true
  #DATABASE_PORT:
  #  external: true
  #RDP_ENCRYPTION_KEY:
  #  external: true
  postgres_password:
    external: true  
  web_postgres_password:
    external: true  
