# Generated by Django 5.1.4 on 2024-12-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='test_type',
            field=models.CharField(choices=[('basic', 'Basic Test'), ('advanced', 'Advanced Test'), ('network', 'Network Test')], default='basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
