# Generated by Django 5.1.4 on 2025-01-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_testrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='accessed_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='accessed_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='is_accessed',
            field=models.BooleanField(default=False),
        ),
    ]
