# Generated by Django 5.1.4 on 2025-01-02 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_testrequest_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='accessed_by_email',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='accessed_by_name',
        ),
        migrations.RemoveField(
            model_name='testrequest',
            name='is_accessed',
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='sub_tests',
            field=models.ManyToManyField(blank=True, to='dashboard.subtest'),
        ),
        migrations.AddField(
            model_name='subtest',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tests', to='dashboard.testtype'),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.testtype'),
        ),
    ]
