# Generated by Django 5.1.4 on 2025-01-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_testrequest_accessed_by_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='docker_container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
