# Generated by Django 5.1.4 on 2025-01-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_testrequest_docker_container_id_alter_subtest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtest',
            name='container_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
