# Generated by Django 5.1.4 on 2025-01-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_subtest_container_name'),
        ('video_playback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='recorded_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_playback.recordedsession'),
        ),
    ]
