# Generated by Django 5.1.4 on 2025-01-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_testrequest_recorded_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequest',
            name='recorded_session',
        ),
        migrations.AddField(
            model_name='testrequest',
            name='video_path',
            field=models.CharField(blank=True, help_text='Path to the S3 video recording for this test.', max_length=255, null=True),
        ),
    ]
