# Generated by Django 5.1.4 on 2025-01-25 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_testrequest_recorded_session_and_more'),
        ('video_playback', '0004_remove_recordedsession_test_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequest',
            name='video_path',
        ),
        migrations.AddField(
            model_name='testrequest',
            name='recorded_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_playback.recordedsession'),
        ),
    ]
