# Generated by Django 5.1.4 on 2025-01-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_testrequest_video_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='recorded_session',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
