# Generated by Django 5.1.4 on 2025-01-30 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_room_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestGroup',
        ),
    ]
