# Generated by Django 5.1.4 on 2025-01-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_room_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
