# Generated by Django 5.1.4 on 2025-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_room_date_created_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtest',
            name='container_name',
        ),
        migrations.AddField(
            model_name='subtest',
            name='ami_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testtype',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=10),
        ),
    ]
