# Generated by Django 5.1.4 on 2025-01-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_subtest_container_name_subtest_ami_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtype',
            name='os_type',
        ),
        migrations.AddField(
            model_name='subtest',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtest',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=10),
        ),
        migrations.AddField(
            model_name='subtest',
            name='time_limit',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
