# Generated by Django 5.1.4 on 2025-01-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_testtype_os_type_subtest_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtest',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
