# Generated by Django 5.1.4 on 2025-02-01 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_company'),
        ('dashboard', '0027_alter_testrequest_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
