# Generated by Django 5.1.4 on 2025-02-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_testrequest_company_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtest',
            name='os_type',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='windows', max_length=10),
        ),
    ]
