# Generated by Django 5.1.4 on 2025-02-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_subtest_os_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='sub_tests',
            field=models.ManyToManyField(to='dashboard.subtest'),
        ),
    ]
