# Generated by Django 5.1.4 on 2025-02-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_testrequest_sub_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequest',
            name='sub_tests',
        ),
        migrations.AddField(
            model_name='testrequest',
            name='sub_tests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subtest'),
            preserve_default=False,
        ),
    ]
