# Generated by Django 5.1.4 on 2025-02-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_testrequest_sub_tests_testrequest_sub_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrequest',
            name='sub_tests',
        ),
        migrations.AddField(
            model_name='testrequest',
            name='sub_tests',
            field=models.ManyToManyField(to='dashboard.subtest'),
        ),
    ]
