# Generated by Django 5.1.4 on 2025-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_testrequest_sub_tests_testrequest_sub_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtest',
            name='pass_fail',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], help_text='Indicates whether the test passed or failed', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subtest',
            name='script',
            field=models.TextField(blank=True, help_text='Command or file path to execute on shutdown', null=True),
        ),
    ]
