# Generated by Django 5.1.4 on 2025-02-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_subtest_pass_fail_subtest_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtest',
            name='pass_fail',
            field=models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('NA', 'na')], help_text='Indicates whether the test passed or failed', max_length=10, null=True),
        ),
    ]
