# Generated by Django 5.2 on 2025-05-07 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_subtest_pass_fail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subtest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtest',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, visible to all users', null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='instance_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='public_ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testtype',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, visible to all users', null=True),
        ),
        migrations.AlterField(
            model_name='testrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_test_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]